name: blossom_server
description: Backend for Blossom Music app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.4
  uuid: ^4.4.0
  collection: ^1.18.0

dev_dependencies:
  shelf_static: ^1.1.2
  http: ^1.2.1
  test: ^1.25.4
