name: blossom_server
description: Backend for Blossom Music app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.4
  uuid: ^3.0.7
  collection: ^1.17.0

dev_dependencies:
  shelf_static: ^1.1.1
  http: ^0.13.6
  test: ^1.21.0
