name: blossom_server
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.2
  shelf_router: ^1.1.4
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
